name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.11.3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_ACCESS_REGION }}

      - name: Terraform Format
        run: terraform fmt -recursive

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2

      - name: Get Instance ID
        id: get-instance-id
        run: echo "INSTANCE_ID=$(terraform output -raw instance_id)" >> $GITHUB_ENV

      - name: Deploy to EC2 using SSM
        env:
          INSTANCE_ID: ${{ env.INSTANCE_ID }}
        run: |
          aws ssm send-command \
            --instance-ids $INSTANCE_ID \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy application" \
            --parameters commands=[
              "cd /home/ec2-user",
              "git clone https://github.com/mtraore-selin/terraform-aws",
              "cd terraform-aws",
              "npm install",
              "npx tsc",
              "pm2 restart dist/index.js"
            ]

      - name: Check SSM Command Status
        run: |
          COMMAND_ID=$(aws ssm send-command \
            --instance-ids $INSTANCE_ID \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy application" \
            --parameters commands=[
              "cd /home/ec2-user",
              "git clone https://github.com/mtraore-selin/terraform-aws",
              "cd terraform-aws",
              "npm install",
              "npx tsc",
              "pm2 restart dist/index.js"
            ] \
            --query "Command.CommandId" \
            --output text)
          aws ssm get-command-invocation \
            --command-id $COMMAND_ID \
            --instance-id $INSTANCE_ID \
            --query "Status" \
            --output text
